# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
      - main  # Branch principal para o pipeline ser acionado

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Instalar dependências'

- task: Docker@2
  inputs:
    containerRegistry: 'nannyspet'  # Referencie seu serviço de registro Docker
    repository: 'wemersonchagas/nannyspet'  # Nome do repositório no Docker Hub ou em outro registro
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)