# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'nannyspet'  # Referencie seu serviço de registro Docker
        repository: 'wemersonchagas/nannyspet'  # Nome do repositório no Docker Hub ou em outro registro
        command: 'buildAndPush'
        dockerfile: '$(Build.SourcesDirectory)/djangoRestApp/Dockerfile'
        tags: |
          $(tag)
