version: '3.5'
services:
 backend:
      container_name: nannys_pets-backend
      image: nannys_pets/backend
      build: 
        context: .
        dockerfile: Dockerfile
      ports:
        - 8000:8000
      volumes:
        - .:/app
      networks:
        - default
