# Generated by Django 5.0.7 on 2025-08-05 02:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaracteristicasCuidador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Porte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        choices=[
                            ("pequeno", "Pequeno"),
                            ("medio", "Médio"),
                            ("grande", "Grande"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cuidador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("sobrenome", models.CharField(max_length=100)),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("senha", models.CharField(default="123456", max_length=128)),
                (
                    "foto_perfil",
                    models.ImageField(
                        blank=True,
                        default="defaults/avatar_padrao.png",
                        upload_to="uploads/",
                    ),
                ),
                ("telefone", models.CharField(max_length=15)),
                ("cep", models.CharField(max_length=8, null=True)),
                ("estado", models.CharField(max_length=100, null=True)),
                ("cidade", models.CharField(max_length=100, null=True)),
                ("rua", models.CharField(max_length=100)),
                ("numero", models.CharField(default="S/N", max_length=10)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("instagram", models.CharField(blank=True, max_length=100, null=True)),
                ("disponivel", models.BooleanField(default=True)),
                (
                    "preco_diaria",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                        verbose_name="Preço por diária",
                    ),
                ),
                (
                    "caracteristicas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="cuidadores",
                        to="nanny_pets_app.caracteristicascuidador",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuidador",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "portes_aceitos",
                    models.ManyToManyField(
                        blank=True, related_name="cuidadores", to="nanny_pets_app.porte"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ImagemAmbiente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foto", models.ImageField(upload_to="ambientes/")),
                (
                    "cuidador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens",
                        to="nanny_pets_app.cuidador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("sobrenome", models.CharField(max_length=100)),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("senha", models.CharField(default="123456", max_length=128)),
                (
                    "foto_perfil",
                    models.ImageField(
                        blank=True,
                        default="defaults/avatar_padrao.png",
                        upload_to="uploads/",
                    ),
                ),
                (
                    "plataforma_indicacao",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("especie", models.CharField(max_length=50)),
                ("raca", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "porte",
                    models.CharField(
                        choices=[
                            ("pequeno", "Pequeno"),
                            ("medio", "Médio"),
                            ("grande", "Grande"),
                        ],
                        max_length=20,
                    ),
                ),
                ("idade", models.PositiveIntegerField()),
                ("castrado", models.BooleanField(default=False)),
                (
                    "genero",
                    models.CharField(
                        choices=[("Macho", "Macho"), ("Fêmea", "Fêmea")], max_length=10
                    ),
                ),
                ("foto", models.ImageField(blank=True, null=True, upload_to="pets/")),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pets",
                        to="nanny_pets_app.tutor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("aprovado", "Aprovado"),
                            ("recusado", "Recusado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendente",
                        max_length=10,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "cuidador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos_recebidos",
                        to="nanny_pets_app.cuidador",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nanny_pets_app.pet",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos",
                        to="nanny_pets_app.tutor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hospedagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmada", "Confirmada"),
                            ("em_andamento", "Em andamento"),
                            ("finalizada", "Finalizada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="confirmada",
                        max_length=20,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                (
                    "cuidador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospedagens",
                        to="nanny_pets_app.cuidador",
                    ),
                ),
                (
                    "pedido",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nanny_pets_app.pedido",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospedagens",
                        to="nanny_pets_app.pet",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospedagens",
                        to="nanny_pets_app.tutor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AvaliacaoCuidador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nota", models.PositiveSmallIntegerField()),
                ("comentario", models.TextField(blank=True)),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "cuidador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="nanny_pets_app.cuidador",
                    ),
                ),
                (
                    "hospedagem",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacao",
                        to="nanny_pets_app.hospedagem",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="nanny_pets_app.tutor",
                    ),
                ),
            ],
        ),
    ]
