# Generated by Django 5.0.7 on 2025-08-03 00:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nanny_pets_app", "0007_alter_cuidador_foto_perfil_alter_tutor_foto_perfil"),
    ]

    operations = [
        migrations.CreateModel(
            name="Porte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        choices=[
                            ("pequeno", "Pequeno"),
                            ("medio", "Médio"),
                            ("grande", "Grande"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cuidador",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cuidador",
            name="preco_diaria",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="Preço por diária",
            ),
        ),
        migrations.AddField(
            model_name="cuidador",
            name="portes_aceitos",
            field=models.ManyToManyField(
                blank=True, related_name="cuidadores", to="nanny_pets_app.porte"
            ),
        ),
    ]
