# Generated by Django 5.0 on 2024-09-04 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanny_pets_app', '0018_alter_caracteristicas_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuidador',
            old_name='cidade',
            new_name='localidade',
        ),
        migrations.RenameField(
            model_name='cuidador',
            old_name='rua',
            new_name='logradouro',
        ),
        migrations.RenameField(
            model_name='cuidador',
            old_name='estado',
            new_name='uf',
        ),
    ]
